# Auto-generated by `make configure` — per-project remote defaults.
# Safe to hand-edit; re-running configure for a cluster overwrites just that line.
REMOTE_alex := /home/atuin/b311bb/b311bb10/lorem-q-work
DEFAULT_CLUSTER := alex
